### ISSUE TITLE
Compatibility with 8 LTS

### ISSUE THREAD

**Issue by Apen** [astehlik/typo3-extension-mediaoembed#10]
Hi,

First, thank for your work 👍 
Have you any plan with the last LTS compatibility?

**Comment by simare** [comment]
Hi,
I am also interested in an LTS Version. What are the open issues here to be compatible to 8.7, maybe we can help?

Best,
Ramon

**Comment by astehlik** [comment]
I updated the develop branch today. It is now compatible with TYPO3 7 and and 8.

I try to make a TER release soon.

**Comment by astehlik** [comment]
Finally a new release was published.
