### ISSUE TITLE
Error 10.4 Youtube

### ISSUE THREAD

**Issue by Zillion01** [astehlik/typo3-extension-mediaoembed#12]
Upon saving the record with a Youtube link:

`2: SQL error: 'Unknown column 'tx_mediaoembed_youtube_rel' in 'field list'' (tt_content:NEW5ff4b141b37c0442678956)`

All typoscript and constants included.
TYPO3 10.4.12
mediaoembed 1.2.0-dev

**Comment by astehlik** [comment]
Thank you for taking the time to create an issue.

I found the problem an will release a fixed version soon.

**Comment by astehlik** [comment]
Version 2.0 was just released. I hope it works for you. Feel free to open a new issue if you experience any problems.

Have a good weekend :smiley:

**Comment by Zillion01** [comment]
Thanks!
